"""empty message

Revision ID: 256d0e247a6b
Revises: bea77e536328
Create Date: 2018-02-10 16:21:00.087330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '256d0e247a6b'
down_revision = 'bea77e536328'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
